from enum import Enum
from typing import List
from pydantic import BaseModel, Field

class Impact(str, Enum):
    """
    Estimated impact on conversion rate.
    """
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"

class Confidence(str, Enum):
    """
    Confidence level in the recommendation based on the evidence.
    """
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"

class Effort(str, Enum):
    """
    Estimated effort to implement the recommendation.
    """
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"

class Opportunity(BaseModel):
    """
    A single CRO recommendation generated by the LLM based on concrete evidence.
    """
    title: str = Field(..., description="Short, actionable title for the opportunity.")
    category: str = Field(..., description="Category of the issue (e.g., 'Navigation', 'Product Page', 'Cart').")
    problem: str = Field(..., description="Description of the issue found.")
    evidence: str = Field(..., description="Specific evidence extracted from the website that proves this issue exists. If missing, say 'Insufficient evidence.'")
    recommendation: str = Field(..., description="Actionable recommendation to fix the issue.")
    impact: Impact = Field(..., description="Estimated impact of the change.")
    confidence: Confidence = Field(..., description="Confidence in the recommendation.")
    effort: Effort = Field(..., description="Estimated effort to implement.")
    experiment: str = Field(..., description="A concrete A/B test idea to validate the recommendation.")
    
class AuditResponse(BaseModel):
    """
    The final output schema expected from the backend, including LLM reasoning and deterministic scoring.
    Note: 'overall_score' and Priority scores are calculated by the backend, not the LLM.
    """
    overall_score: int = Field(0, description="Calculated overall CRO score (0-100). Generated by Backend.")
    executive_summary: str = Field(..., description="A high-level summary of the store's current state based on evidence.")
    quick_wins: List[str] = Field(..., description="List of immediate, low-effort high-impact actions.")
    long_term_improvements: List[str] = Field(..., description="List of strategic, higher-effort improvements.")
    opportunities: List[Opportunity] = Field(..., description="List of all prioritized CRO opportunities.")
